name: Bundle for FuzzCorp
on:
  repository_dispatch:
    types: [sig, solfuzz_main, solfuzz_agave]
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sig-fuzz
        uses: actions/checkout@v4

      - name: Checkout Sig
        uses: actions/checkout@v4
        with:
          repository: Syndica/sig
          path: sig/

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build sig-fuzz
        run: zig build -Dcpu=haswell --summary all

      - name: Download Artifacts
        env: 
          PAT: ${{ secrets.PAT }}
        run: ./scripts/download_artifacts.sh
      - name: Bundle
        run: ./scripts/bundle.sh

      - name: upload to FuzzCorp
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AKID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SKID }}
          AWS_DEFAULT_REGION: us-east-2
        run: |
          aws s3 cp ./bundle/fuzz.zip s3://fuzzcorp-bundle-dropbox-975049986498-86c13d2/org_AAAAAAAT/prj_AAAAAAATADU/$(date +%s).zip
 
