name: Bundle for FuzzCorp
on:
  repository_dispatch:
    types: [sig, solfuzz_main, solfuzz_agave]
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sig-fuzz
        uses: actions/checkout@v4

      - name: Checkout Sig
        uses: actions/checkout@v4
        with:
          repository: Syndica/sig
          path: sig/

      - name: Setup Zig
        uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0

      - name: Build sig-fuzz
        run: zig build -Dcpu=haswell --summary all

      - name: Download solfuzz_agave Artifacts
        env: 
          PAT: ${{ secrets.PAT }}
        run: ./scripts/download_artifacts.sh

      - name: Download SolFuzz Artifacts
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.PAT }}
          repository: firedancer-io/solfuzz
          run-id: ${{ github.event.client_payload.run_id}}
          name: solfuzz-bins
          path: ./temp
    
      - name: Bundle
        run: ./scripts/bundle.sh

      - run: ls -R bundle

      - run: |
          mkdir result
          unzip bundle/fuzz.zip -d result/
 
